/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 185
#define YY_END_OF_BUFFER 186
static yyconst short int yy_acclist[739] =
    {   0,
      186,  184,  185,  183,  184,  185,  183,  185,  162,  184,
      185,  159,  184,  185,  163,  184,  185,  172,  184,  185,
      173,  184,  185,  157,  184,  185,  155,  184,  185,  169,
      184,  185,  156,  184,  185,  168,  184,  185,  158,  184,
      185,  181,  184,  185,  171,  184,  185,  178,  184,  185,
      160,  184,  185,  167,  184,  185,  161,  184,  185,  170,
      184,  185,  174,  184,  185,  175,  184,  185,  165,  184,
      185,  182,  184,  185,  182,  184,  185,  182,  184,  185,
      182,  184,  185,  182,  184,  185,  182,  184,  185,  182,
      184,  185,  182,  184,  185,  182,  184,  185,  182,  184,

      185,  182,  184,  185,  182,  184,  185,  182,  184,  185,
      182,  184,  185,  182,  184,  185,  182,  184,  185,  182,
      184,  185,  182,  184,  185,  182,  184,  185,  182,  184,
      185,  182,  184,  185,  182,  184,  185,  176,  184,  185,
      164,  184,  185,  177,  184,  185,  166,  184,  185,  183,
      144,  145,  142,  128,  141,  129,  149,  151,  179,  143,
      181,  180,  150,  137,  138,  147,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,   18,  182,  182,  182,  135,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,

      182,  182,   27,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,   33,  140,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  146,  148,  179,  130,
      132,  131,   70,  182,  182,    3,  139,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,   60,
      182,  182,  182,  182,  182,  182,   81,  182,  182,  182,
      182,  182,  182,  182,   86,  182,   83,  182,  182,  182,
      182,  182,  182,   91,  182,  182,  182,   24,  182,  182,

      182,  182,  182,  134,  182,  182,  182,  182,    1,  182,
      182,  182,  182,  102,  182,  182,  182,  182,  133,  182,
      182,  182,  110,  182,  182,  136,  182,   30,  153,  182,
      182,   31,  182,  182,  182,  114,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  121,  182,  182,
      182,  182,  182,  182,  182,  124,  182,  182,  182,  182,
      182,  182,   49,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,   56,  182,  179,   71,  182,  182,
       73,  182,   75,  182,  182,  182,    7,  182,  182,    9,
      182,  182,   78,  182,   79,  182,   58,  182,   11,  182,

      182,   59,  182,  182,  182,  182,  182,   82,  182,   61,
      182,  182,  182,  182,   20,  182,   21,  182,   87,  182,
       84,  182,  182,   88,  182,  182,   89,  182,  182,  182,
      182,   92,  182,   93,  182,   94,  182,  182,  182,  182,
       26,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      105,  182,  106,  182,   28,  182,  182,  182,  109,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  117,  182,  182,  182,  182,  182,  122,  182,
      182,  182,  123,  182,  182,  182,  182,  125,  182,  182,
      182,   46,  182,  182,   48,  182,  182,  182,  182,  182,

      182,   54,  182,  182,   64,  182,  182,  182,  182,  182,
       72,  182,  182,   74,  182,   76,  182,   77,  182,  182,
        6,  182,    8,  182,   10,  182,   12,  182,   13,  182,
       14,  182,  182,  182,  182,  182,  182,   85,  182,   22,
      182,  182,   23,  182,   90,  182,   95,  182,  182,  182,
       96,  182,  182,   97,  182,   98,  182,  182,  182,  182,
      103,  182,  104,  182,  107,  182,  182,  182,  182,  182,
      182,  182,  182,   34,  182,  182,  182,  182,  182,  182,
      182,  118,  182,  182,   38,  182,  182,  182,  182,  182,
      182,  182,  182,  182,   47,  182,  127,  182,  182,  182,

       52,  182,  182,   62,  182,   63,  182,   65,  182,   55,
      182,  182,    4,  182,    5,  182,  182,  182,  182,   17,
      154,  182,   19,  182,  182,   25,  182,  182,  182,   99,
      182,  100,  182,  182,  108,  182,  182,  182,  182,  182,
       32,  182,  182,  182,  182,   37,  182,  182,  116,  182,
        2,  182,  182,  120,  182,   39,  182,   40,  152,  182,
      182,   41,  182,   43,  182,   44,  182,  182,  126,  182,
      182,  182,  182,   57,  182,  182,  182,   16,  182,   66,
      182,   67,  182,  182,  101,  182,  182,  182,  182,  182,
      182,   35,  182,  182,  182,  119,  182,  182,  182,   50,

      182,  182,   53,  182,   15,  182,   80,  182,   68,  182,
      182,  182,  182,  182,   69,  182,  182,  182,  182,   45,
      182,   51,  182,   29,  182,  111,  182,  112,  182,  182,
       36,  182,  115,  182,   42,  182,  113,  182
    } ;

static yyconst short int yy_accept[513] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   18,
       21,   24,   27,   30,   33,   36,   39,   42,   45,   48,
       51,   54,   57,   60,   63,   66,   69,   72,   75,   78,
       81,   84,   87,   90,   93,   96,   99,  102,  105,  108,
      111,  114,  117,  120,  123,  126,  129,  132,  135,  138,
      141,  144,  147,  150,  151,  152,  153,  154,  155,  156,
      157,  158,  159,  159,  160,  161,  162,  163,  164,  165,
      165,  166,  167,  168,  169,  170,  171,  172,  173,  174,
      175,  176,  177,  178,  179,  180,  181,  182,  183,  184,
      186,  187,  188,  190,  191,  192,  193,  194,  195,  196,

      197,  198,  199,  200,  201,  202,  203,  205,  206,  207,
      208,  209,  210,  211,  212,  213,  214,  215,  216,  217,
      218,  221,  222,  223,  224,  225,  226,  227,  228,  229,
      230,  231,  232,  233,  234,  235,  236,  237,  238,  239,
      240,  241,  242,  243,  244,  245,  246,  247,  248,  249,
      249,  249,  250,  251,  252,  253,  255,  256,  259,  260,
      261,  262,  263,  264,  265,  266,  267,  268,  269,  270,
      272,  273,  274,  275,  276,  277,  279,  280,  281,  282,
      283,  284,  285,  287,  289,  290,  291,  292,  293,  294,
      296,  297,  298,  300,  301,  302,  303,  304,  306,  307,

      308,  309,  311,  312,  313,  314,  316,  317,  318,  319,
      321,  322,  323,  325,  326,  328,  331,  332,  334,  335,
      336,  338,  339,  340,  341,  342,  343,  344,  345,  346,
      347,  348,  350,  351,  352,  353,  354,  355,  356,  358,
      359,  360,  361,  362,  363,  365,  366,  367,  368,  369,
      370,  371,  372,  373,  374,  375,  377,  378,  380,  381,
      383,  385,  386,  387,  389,  390,  392,  393,  395,  397,
      399,  401,  402,  404,  405,  406,  407,  408,  410,  412,
      413,  414,  415,  417,  419,  421,  423,  424,  426,  427,
      429,  430,  431,  432,  434,  436,  438,  439,  440,  441,

      443,  444,  445,  446,  447,  448,  449,  450,  451,  453,
      455,  457,  458,  459,  461,  462,  463,  464,  465,  466,
      467,  468,  469,  470,  471,  472,  473,  475,  476,  477,
      478,  479,  481,  482,  483,  485,  486,  487,  488,  490,
      491,  492,  494,  495,  497,  498,  499,  500,  501,  502,
      504,  505,  507,  508,  509,  510,  511,  513,  514,  516,
      518,  520,  521,  523,  525,  527,  529,  531,  533,  534,
      535,  536,  537,  538,  540,  542,  543,  545,  547,  549,
      550,  551,  553,  554,  556,  558,  559,  560,  561,  563,
      565,  567,  568,  569,  570,  571,  572,  573,  574,  576,

      577,  578,  579,  580,  581,  582,  584,  585,  587,  588,
      589,  590,  591,  592,  593,  594,  595,  597,  599,  600,
      601,  603,  604,  606,  608,  610,  612,  613,  615,  617,
      618,  619,  620,  623,  625,  626,  628,  629,  630,  632,
      634,  635,  637,  638,  639,  640,  641,  643,  644,  645,
      646,  648,  649,  651,  653,  654,  656,  658,  661,  662,
      664,  666,  668,  669,  671,  672,  673,  674,  676,  677,
      678,  680,  682,  684,  685,  687,  688,  689,  690,  691,
      692,  694,  695,  696,  698,  699,  700,  702,  703,  705,
      707,  709,  711,  712,  713,  714,  715,  717,  718,  719,

      720,  722,  724,  726,  728,  730,  731,  733,  735,  737,
      739,  739
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    1,    5,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       25,    1,   26,   27,   28,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[516] =
    {   0,
        0,    0,  541,  542,   57,   59,  542,  518,  517,  542,
      542,  516,   53,  542,   53,  528,   55,   55,  517,  542,
       45,  542,  512,  542,  542,  542,  512,    0,   48,   37,
       64,   48,   63,   81,   39,  480,   72,   91,  489,   55,
       65,   43,   92,  105,  111,   91,  108,  112,  488,  542,
      508,  542,  542,  114,  542,  542,  542,  542,  542,  542,
      520,  542,  519,    0,  542,  143,  150,  542,  505,  503,
      503,  542,    0,  477,  480,  490,  484,  491,  471,  475,
      484,   72,  470,  117,  486,  472,  126,  129,  140,  464,
      465,  462,    0,  476,  465,  122,  471,  467,  463,  146,

      459,  144,  456,  455,  469,  457,  453,  456,  450,  464,
      467,  449,  137,  145,  461,  461,  143,  157,  444,  444,
      462,  438,  150,  458,  149,  445,  437,  456,  441,  156,
      450,  436,   39,  444,  438,  438,  449,  155,  146,  433,
      429,  438,  428,  436,  163,  435,  425,  542,  542,  461,
      198,    0,  542,  542,  542,    0,  422,  440,  425,  424,
      175,  425,  435,  430,  431,  413,  420,  413,  412,    0,
      410,  421,  411,  166,  401,  417,  404,  422,  417,  419,
      415,  406,  415,  188,  398,  397,  402,  409,  182,  389,
      398,  407,    0,  386,  404,  390,  392,    0,  391,  385,

      397,    0,  379,  389,  178,  200,  394,  386,  378,    0,
      392,  392,    0,  378,    0,    0,  375,  394,  373,  387,
        0,  369,  370,  377,  190,  367,  367,  372,  373,  366,
      369,  374,  376,  377,  359,  358,  356,  356,  367,  358,
      360,  353,  356,  189,    0,  365,  360,  354,  347,  362,
      347,  350,  348,  341,  349,  360,  378,  350,  352,  348,
      203,  341,  336,    0,  342,    0,  344,    0,    0,    0,
        0,  332,    0,  338,  329,  339,  328,    0,    0,  325,
      325,  332,    0,    0,    0,    0,  355,    0,  337,    0,
      339,  320,  321,    0,    0,    0,  322,  323,  331,    0,

      315,  316,  331,  316,  318,  316,  308,  179,    0,    0,
        0,  308,  313,    0,  307,  323,  195,  319,  305,  305,
      320,  315,  310,  309,  296,  298,    0,  311,  312,  293,
      307,    0,  296,  301,    0,  300,  305,  304,    0,  294,
      292,    0,  281,    0,  300,  298,  294,  293,  278,    0,
      280,    0,  290,  276,  290,  289,    0,  276,    0,    0,
        0,  288,    0,    0,    0,    0,    0,    0,  277,  281,
      277,  283,  282,    0,    0,  265,    0,    0,    0,  281,
      283,    0,  278,    0,    0,  281,  261,  266,    0,    0,
        0,  275,  262,  252,  270,  260,  257,  268,    0,  252,

      268,  267,  255,  253,  253,    0,   90,    0,  262,  259,
      258,  260,  242,  253,  259,  258,    0,    0,  253,  243,
        0,  255,    0,    0,    0,    0,  238,    0,    0,  233,
      246,  232,    0,    0,  245,    0,  237,  248,    0,    0,
      244,    0,  246,  237,  225,  221,    0,  242,  237,  221,
        0,  236,    0,    0,  225,    0,    0,    0,  229,    0,
        0,    0,  217,    0,  230,  230,  222,    0,  228,  218,
        0,    0,    0,  218,    0,  227,  215,  223,  226,  213,
        0,  218,  209,    0,  208,  207,    0,  206,    0,    0,
        0,    0,  204,  188,  188,  187,    0,  200,  182,  180,

        0,    0,    0,    0,    0,  194,    0,    0,    0,    0,
      542,   99,  241,  245,  249
    } ;

static yyconst short int yy_def[516] =
    {   0,
      511,    1,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  512,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  514,  515,  511,  512,  512,  511,  511,  511,
      511,  511,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  511,  511,  514,
      514,  515,  511,  511,  511,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  514,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
        0,  511,  511,  511,  511
    } ;

static yyconst short int yy_nxt[601] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   18,   18,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   28,   28,   38,
       39,   40,   41,   42,   28,   43,   44,   45,   46,   47,
       48,   49,   28,   28,   50,   51,   52,   53,   54,   54,
       54,   54,   58,   63,   60,   69,   70,  236,   64,   66,
       66,   66,   66,   79,   59,   61,   65,   74,   75,   80,
       89,  104,   81,  117,  237,  122,  105,  118,  123,   76,
       90,  124,   82,   83,   77,   78,   84,  119,  120,   85,

       86,   67,   91,   87,   92,  107,   88,   93,   94,   96,
      121,  108,   97,  109,   95,   54,   54,   98,  164,  165,
       99,  100,  110,  101,  125,  111,  102,  103,  126,  455,
      112,  456,  141,  113,  127,  128,  114,  142,  115,  135,
      129,  130,  145,  136,  143,  137,  138,  146,  131,  132,
      144,  185,  133,  167,  171,  134,  139,   66,   66,   66,
       66,  186,  168,  140,  511,  511,  511,  511,  172,  173,
      174,  206,  175,  178,  190,  176,  194,  177,  207,  179,
      195,  208,  191,  212,  213,  214,  222,  209,  192,  225,
      231,  242,  223,  389,  244,  251,  226,  232,  245,  252,

      243,  215,  253,  262,  286,  254,  151,  216,  217,  233,
      292,  257,  275,  276,  306,  308,  309,  263,  324,  360,
      307,  344,  390,  395,  293,  510,  509,  508,  287,  310,
      345,  507,  506,  505,  325,  504,  503,  502,  361,  501,
      500,  499,  396,   73,   73,  150,  150,  150,  150,  152,
      498,  152,  152,  497,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  486,  485,  484,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  471,
      470,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  454,  453,  452,  451,  450,  449,

      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  401,  400,  399,
      398,  397,  394,  393,  392,  391,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  359,  358,  357,  151,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  343,  342,

      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  291,  290,  289,  288,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  261,  260,  259,  258,  151,
      256,  255,  250,  249,  248,  247,  246,  241,  240,  239,
      238,  235,  234,  230,  229,  228,  227,  224,  221,  220,
      219,  218,  211,  210,  205,  204,  203,  202,  201,  200,

      199,  198,  197,  196,  193,  189,  188,  187,  184,  183,
      182,  181,  180,  170,  169,  166,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  151,  149,  148,
      147,  116,  106,   72,   71,   68,   62,   57,   56,   55,
      511,    3,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511

    } ;

static yyconst short int yy_chk[601] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        6,    6,   13,   17,   15,   21,   21,  133,   17,   18,
       18,   18,   18,   30,   13,   15,   17,   29,   29,   30,
       32,   35,   30,   40,  133,   42,   35,   40,   42,   29,
       32,   42,   31,   31,   29,   29,   31,   40,   41,   31,

       31,  512,   33,   31,   33,   37,   31,   33,   33,   34,
       41,   37,   34,   37,   33,   54,   54,   34,   82,   82,
       34,   34,   38,   34,   43,   38,   34,   34,   43,  407,
       38,  407,   46,   38,   43,   44,   38,   46,   38,   45,
       44,   44,   48,   45,   47,   45,   45,   48,   44,   44,
       47,   96,   44,   84,   87,   44,   45,   66,   66,   66,
       66,   96,   84,   45,   67,   67,   67,   67,   87,   88,
       88,  113,   88,   89,  100,   88,  102,   88,  113,   89,
      102,  114,  100,  117,  117,  118,  123,  114,  100,  125,
      130,  138,  123,  308,  139,  145,  125,  130,  139,  145,

      138,  118,  145,  161,  184,  145,  151,  118,  118,  130,
      189,  151,  174,  174,  205,  206,  206,  161,  225,  261,
      205,  244,  308,  317,  189,  506,  500,  499,  184,  206,
      244,  498,  496,  495,  225,  494,  493,  488,  261,  486,
      485,  483,  317,  513,  513,  514,  514,  514,  514,  515,
      482,  515,  515,  480,  479,  478,  477,  476,  474,  470,
      469,  467,  466,  465,  463,  459,  455,  452,  450,  449,
      448,  446,  445,  444,  443,  441,  438,  437,  435,  432,
      431,  430,  427,  422,  420,  419,  416,  415,  414,  413,
      412,  411,  410,  409,  405,  404,  403,  402,  401,  400,

      398,  397,  396,  395,  394,  393,  392,  388,  387,  386,
      383,  381,  380,  376,  373,  372,  371,  370,  369,  362,
      358,  356,  355,  354,  353,  351,  349,  348,  347,  346,
      345,  343,  341,  340,  338,  337,  336,  334,  333,  331,
      330,  329,  328,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  316,  315,  313,  312,  307,  306,  305,  304,
      303,  302,  301,  299,  298,  297,  293,  292,  291,  289,
      287,  282,  281,  280,  277,  276,  275,  274,  272,  267,
      265,  263,  262,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  243,  242,

      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  224,  223,  222,  220,
      219,  218,  217,  214,  212,  211,  209,  208,  207,  204,
      203,  201,  200,  199,  197,  196,  195,  194,  192,  191,
      190,  188,  187,  186,  185,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  173,  172,  171,  169,  168,  167,
      166,  165,  164,  163,  162,  160,  159,  158,  157,  150,
      147,  146,  144,  143,  142,  141,  140,  137,  136,  135,
      134,  132,  131,  129,  128,  127,  126,  124,  122,  121,
      120,  119,  116,  115,  112,  111,  110,  109,  108,  107,

      106,  105,  104,  103,  101,   99,   98,   97,   95,   94,
       92,   91,   90,   86,   85,   83,   81,   80,   79,   78,
       77,   76,   75,   74,   71,   70,   69,   63,   61,   51,
       49,   39,   36,   27,   23,   19,   16,   12,    9,    8,
        3,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 3 "lexer.l"
    #include "parser.tab.h"
    #include <ctype.h>   
    char* to_upper(char* text) {
        for (int i = 0; text[i] != '\0'; i++) {
            text[i] = toupper(text[i]);
        }
        return text;    
    }
#line 767 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 24 "lexer.l"


    /* Keywords */

#line 923 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 512 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 542 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 28 "lexer.l"
{ printf("\nKeyword: %s\n", yytext); return INT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "lexer.l"
{ printf("\nKeyword: %s\n", yytext); return RETURN; }
	YY_BREAK
case 3:
#line 31 "lexer.l"
case 4:
#line 32 "lexer.l"
case 5:
#line 33 "lexer.l"
case 6:
#line 34 "lexer.l"
case 7:
YY_RULE_SETUP
#line 34 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return BOOL;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return BREAK;}
	YY_BREAK
case 9:
#line 37 "lexer.l"
case 10:
#line 38 "lexer.l"
case 11:
#line 39 "lexer.l"
case 12:
#line 40 "lexer.l"
case 13:
#line 41 "lexer.l"
case 14:
#line 42 "lexer.l"
case 15:
YY_RULE_SETUP
#line 42 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return CONTINUE;}
	YY_BREAK
case 16:
#line 44 "lexer.l"
case 17:
#line 45 "lexer.l"
case 18:
YY_RULE_SETUP
#line 45 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return DO;}
	YY_BREAK
case 19:
#line 47 "lexer.l"
case 20:
YY_RULE_SETUP
#line 47 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return ELSE;}
	YY_BREAK
case 21:
#line 49 "lexer.l"
case 22:
#line 50 "lexer.l"
case 23:
YY_RULE_SETUP
#line 50 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return FLOAT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return FOR;}
	YY_BREAK
case 25:
#line 53 "lexer.l"
case 26:
#line 54 "lexer.l"
case 27:
YY_RULE_SETUP
#line 54 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return IF;}
	YY_BREAK
case 28:
#line 56 "lexer.l"
case 29:
#line 57 "lexer.l"
case 30:
#line 58 "lexer.l"
case 31:
#line 59 "lexer.l"
case 32:
#line 60 "lexer.l"
case 33:
#line 61 "lexer.l"
case 34:
#line 62 "lexer.l"
case 35:
#line 63 "lexer.l"
case 36:
#line 64 "lexer.l"
case 37:
#line 65 "lexer.l"
case 38:
#line 66 "lexer.l"
case 39:
#line 67 "lexer.l"
case 40:
#line 68 "lexer.l"
case 41:
#line 69 "lexer.l"
case 42:
#line 70 "lexer.l"
case 43:
#line 71 "lexer.l"
case 44:
#line 72 "lexer.l"
case 45:
#line 73 "lexer.l"
case 46:
#line 74 "lexer.l"
case 47:
#line 75 "lexer.l"
case 48:
#line 76 "lexer.l"
case 49:
#line 77 "lexer.l"
case 50:
#line 78 "lexer.l"
case 51:
#line 79 "lexer.l"
case 52:
#line 80 "lexer.l"
case 53:
#line 81 "lexer.l"
case 54:
YY_RULE_SETUP
#line 81 "lexer.l"
{ printf("\nKeyword: %s\n", yytext); return VOID; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "lexer.l"
{ printf("\nKeyword: %s\n", yytext); return WHILE; }
	YY_BREAK
case 56:
#line 84 "lexer.l"
case 57:
#line 85 "lexer.l"
case 58:
#line 86 "lexer.l"
case 59:
#line 87 "lexer.l"
case 60:
#line 88 "lexer.l"
case 61:
#line 89 "lexer.l"
case 62:
#line 90 "lexer.l"
case 63:
#line 91 "lexer.l"
case 64:
#line 92 "lexer.l"
case 65:
#line 93 "lexer.l"
case 66:
#line 94 "lexer.l"
case 67:
#line 95 "lexer.l"
case 68:
#line 96 "lexer.l"
case 69:
#line 97 "lexer.l"
case 70:
#line 98 "lexer.l"
case 71:
#line 99 "lexer.l"
case 72:
#line 100 "lexer.l"
case 73:
#line 101 "lexer.l"
case 74:
#line 102 "lexer.l"
case 75:
#line 103 "lexer.l"
case 76:
#line 104 "lexer.l"
case 77:
#line 105 "lexer.l"
case 78:
#line 106 "lexer.l"
case 79:
#line 107 "lexer.l"
case 80:
#line 108 "lexer.l"
case 81:
#line 109 "lexer.l"
case 82:
#line 110 "lexer.l"
case 83:
#line 111 "lexer.l"
case 84:
#line 112 "lexer.l"
case 85:
#line 113 "lexer.l"
case 86:
#line 114 "lexer.l"
case 87:
#line 115 "lexer.l"
case 88:
#line 116 "lexer.l"
case 89:
#line 117 "lexer.l"
case 90:
#line 118 "lexer.l"
case 91:
#line 119 "lexer.l"
case 92:
#line 120 "lexer.l"
case 93:
#line 121 "lexer.l"
case 94:
#line 122 "lexer.l"
case 95:
#line 123 "lexer.l"
case 96:
#line 124 "lexer.l"
case 97:
#line 125 "lexer.l"
case 98:
#line 126 "lexer.l"
case 99:
#line 127 "lexer.l"
case 100:
#line 128 "lexer.l"
case 101:
#line 129 "lexer.l"
case 102:
#line 130 "lexer.l"
case 103:
#line 131 "lexer.l"
case 104:
#line 132 "lexer.l"
case 105:
#line 133 "lexer.l"
case 106:
#line 134 "lexer.l"
case 107:
#line 135 "lexer.l"
case 108:
#line 136 "lexer.l"
case 109:
#line 137 "lexer.l"
case 110:
#line 138 "lexer.l"
case 111:
#line 139 "lexer.l"
case 112:
#line 140 "lexer.l"
case 113:
#line 141 "lexer.l"
case 114:
#line 142 "lexer.l"
case 115:
#line 143 "lexer.l"
case 116:
#line 144 "lexer.l"
case 117:
#line 145 "lexer.l"
case 118:
#line 146 "lexer.l"
case 119:
#line 147 "lexer.l"
case 120:
#line 148 "lexer.l"
case 121:
#line 149 "lexer.l"
case 122:
#line 150 "lexer.l"
case 123:
#line 151 "lexer.l"
case 124:
#line 152 "lexer.l"
case 125:
#line 153 "lexer.l"
case 126:
#line 154 "lexer.l"
case 127:
YY_RULE_SETUP
#line 154 "lexer.l"
{yytext = to_upper(yytext);printf("\nKeyword: %s\n", yytext);return *yytext;}   
	YY_BREAK
/************/
/* Operators */
case 128:
#line 159 "lexer.l"
case 129:
#line 160 "lexer.l"
case 130:
#line 161 "lexer.l"
case 131:
#line 162 "lexer.l"
case 132:
#line 163 "lexer.l"
case 133:
YY_RULE_SETUP
#line 163 "lexer.l"
{printf("\nOperator: %s\n", yytext); return LTE;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 164 "lexer.l"
{printf("\nOperator: %s\n", yytext); return GTE;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 165 "lexer.l"
{printf("\nOperator: %s\n", yytext); return EQ;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 166 "lexer.l"
{printf("\nOperator: %s\n", yytext); return NEQ;}
	YY_BREAK
case 137:
#line 168 "lexer.l"
case 138:
#line 169 "lexer.l"
case 139:
YY_RULE_SETUP
#line 169 "lexer.l"
{printf("\nOperator: %s\n", yytext); return AND;}             
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 170 "lexer.l"
{printf("\nOperator: %s\n", yytext); return OR;}              
	YY_BREAK
case 141:
#line 172 "lexer.l"
case 142:
#line 173 "lexer.l"
case 143:
#line 174 "lexer.l"
case 144:
#line 175 "lexer.l"
case 145:
#line 176 "lexer.l"
case 146:
#line 177 "lexer.l"
case 147:
#line 178 "lexer.l"
case 148:
#line 179 "lexer.l"
case 149:
#line 180 "lexer.l"
case 150:
#line 181 "lexer.l"
case 151:
#line 182 "lexer.l"
case 152:
#line 183 "lexer.l"
case 153:
#line 184 "lexer.l"
case 154:
#line 185 "lexer.l"
case 155:
#line 186 "lexer.l"
case 156:
#line 187 "lexer.l"
case 157:
#line 188 "lexer.l"
case 158:
#line 189 "lexer.l"
case 159:
#line 190 "lexer.l"
case 160:
YY_RULE_SETUP
#line 190 "lexer.l"
{printf("\nOperator: %s\n", yytext); return '<';}              
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 191 "lexer.l"
{printf("\nOperator: %s\n", yytext); return '>';}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 192 "lexer.l"
{printf("\nOperator: %s\n", yytext); return NOT;}                    
	YY_BREAK
case 163:
#line 194 "lexer.l"
case 164:
#line 195 "lexer.l"
case 165:
#line 196 "lexer.l"
case 166:
#line 197 "lexer.l"
case 167:
#line 198 "lexer.l"
case 168:
#line 199 "lexer.l"
case 169:
#line 200 "lexer.l"
case 170:
#line 201 "lexer.l"
case 171:
#line 202 "lexer.l"
case 172:
#line 203 "lexer.l"
case 173:
#line 204 "lexer.l"
case 174:
#line 205 "lexer.l"
case 175:
#line 206 "lexer.l"
case 176:
#line 207 "lexer.l"
case 177:
#line 208 "lexer.l"
case 178:
YY_RULE_SETUP
#line 208 "lexer.l"
{printf("\nOperator: %s\n", yytext); return *yytext;}
	YY_BREAK
/************/
case 179:
YY_RULE_SETUP
#line 211 "lexer.l"
{printf("\nCommend: { %s }\n", yytext);/*ignore further*/}
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 212 "lexer.l"
{fprintf(stderr, "\nError at line %d: Invalid number '%s'\n", yylineno, yytext);}
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 213 "lexer.l"
{printf("\nInteger: %s\n", yytext); return INTEGER;}
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 214 "lexer.l"
{printf("\nIdentifier: %s\n", yytext); return IDENTIFIER;}
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 215 "lexer.l"
{/* Ignore whitespace*/}
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 216 "lexer.l"
{printf("\nUnknown character: %s\n", yytext); return *yytext;}
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 218 "lexer.l"
ECHO;
	YY_BREAK
#line 1477 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 512 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 512 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 511);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 218 "lexer.l"

int yywrap() {
    return 1;
}