/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 189
#define YY_END_OF_BUFFER 190
static yyconst short int yy_acclist[746] =
    {   0,
      190,  188,  189,  187,  188,  189,  187,  189,  161,  188,
      189,  188,  189,  158,  188,  189,  163,  188,  189,  188,
      189,  172,  188,  189,  173,  188,  189,  156,  188,  189,
      154,  188,  189,  169,  188,  189,  155,  188,  189,  168,
      188,  189,  157,  188,  189,  181,  188,  189,  171,  188,
      189,  178,  188,  189,  159,  188,  189,  167,  188,  189,
      160,  188,  189,  170,  188,  189,  174,  188,  189,  175,
      188,  189,  165,  188,  189,  186,  188,  189,  186,  188,
      189,  186,  188,  189,  186,  188,  189,  186,  188,  189,
      186,  188,  189,  186,  188,  189,  186,  188,  189,  186,

      188,  189,  186,  188,  189,  186,  188,  189,  186,  188,
      189,  186,  188,  189,  186,  188,  189,  186,  188,  189,
      186,  188,  189,  186,  188,  189,  186,  188,  189,  186,
      188,  189,  186,  188,  189,  186,  188,  189,  186,  188,
      189,  176,  188,  189,  164,  188,  189,  177,  188,  189,
      166,  188,  189,  187,  135,  184,  143,  138,  144,  185,
      141,  127,  140,  128,  148,  150,  179,  142,  181,  180,
      149,  136,  132,  134,  133,  137,  146,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,    8,  186,  186,  186,  186,  186,

      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
       12,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,   15,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  145,  139,  183,  185,  185,  183,  183,  147,
      179,  182,  129,  131,  130,   69,  186,  186,    3,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,   59,  186,  186,  186,  186,  186,  186,   80,  186,
      186,  186,  186,  186,  186,  186,   85,  186,   82,  186,

      186,  186,  186,  186,  186,   90,  186,  186,  186,   11,
      186,  186,  186,  186,  186,  186,  186,  186,    1,  186,
      186,  186,  186,  101,  186,  186,  186,  186,  186,  186,
      109,  186,  186,   35,  152,  186,  186,  162,  186,  186,
      186,  113,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  120,  186,  186,  186,  186,  186,  186,
      186,  123,  186,  186,  186,  186,  186,  186,   50,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
       55,  186,  179,   70,  186,  186,   72,  186,   74,  186,
      186,  186,    4,  186,  186,   23,  186,  186,   77,  186,

       78,  186,   57,  186,    6,  186,  186,   58,  186,  186,
      186,  186,  186,   81,  186,   60,  186,  186,  186,  186,
        9,  186,   30,  186,   86,  186,   83,  186,  186,   87,
      186,  186,   88,  186,  186,  186,  186,   91,  186,   92,
      186,   93,  186,  186,  186,  186,   32,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  104,  186,  105,  186,
       33,  186,  186,  186,  108,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  116,  186,  186,
      186,  186,  186,  121,  186,  186,  186,  122,  186,  186,
      186,  186,  186,  124,  186,  186,  186,   48,  186,  186,

       18,  186,  186,  186,  186,  186,  186,   13,  186,  186,
       63,  186,  186,  186,  186,  186,  182,   71,  186,  186,
       73,  186,   75,  186,   76,  186,  186,   22,  186,    5,
      186,   24,  186,   25,  186,   26,  186,   16,  186,  186,
      186,  186,  186,  186,   84,  186,   17,  186,  186,   10,
      186,   89,  186,   94,  186,  186,  186,   95,  186,  186,
       96,  186,   97,  186,  186,  186,  186,  102,  186,  103,
      186,  106,  186,  186,  186,  186,  186,  186,  186,   36,
      186,  186,  186,  186,  186,  186,  186,  117,  186,  186,
       40,  186,  186,  186,  186,  186,  186,  186,  186,  186,

      186,   49,  186,  126,  186,  186,  186,   53,  186,  186,
       61,  186,   62,  186,   64,  186,   14,  186,  186,   20,
      186,   21,  186,  186,  186,  186,   28,  153,  186,   29,
      186,  186,   31,  186,  186,  186,   98,  186,   99,  186,
      186,  107,  186,  186,  186,  186,  186,  186,  186,  186,
       39,  186,  186,  115,  186,    2,  186,  186,  119,  186,
       41,  186,   42,  151,  186,  186,   43,  186,   19,  186,
       45,  186,   46,  186,  186,  125,  186,  186,  186,  186,
       56,  186,  186,  186,   27,  186,   65,  186,   66,  186,
      186,  100,  186,  186,  186,  186,  186,  186,   37,  186,

      186,  186,  118,  186,  186,  186,   51,  186,  186,   54,
      186,    7,  186,   79,  186,   67,  186,  186,  186,  186,
      186,   68,  186,  186,  186,  186,   47,  186,   52,  186,
       34,  186,  110,  186,  111,  186,  186,   38,  186,  114,
      186,   44,  186,  112,  186
    } ;

static yyconst short int yy_accept[531] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       20,   22,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  112,  115,  118,  121,  124,  127,  130,  133,  136,
      139,  142,  145,  148,  151,  154,  155,  156,  156,  157,
      157,  158,  159,  160,  160,  160,  161,  161,  162,  163,
      164,  165,  166,  167,  167,  168,  169,  169,  170,  171,
      172,  173,  174,  175,  176,  177,  178,  179,  180,  181,
      182,  183,  184,  185,  186,  187,  188,  189,  190,  191,

      192,  193,  194,  195,  197,  198,  199,  200,  201,  202,
      203,  204,  205,  206,  207,  208,  209,  210,  211,  213,
      214,  215,  216,  217,  218,  219,  220,  221,  222,  223,
      224,  225,  227,  228,  229,  230,  231,  232,  233,  234,
      235,  236,  237,  238,  239,  240,  241,  242,  243,  244,
      245,  246,  247,  248,  249,  250,  251,  252,  253,  254,
      255,  257,  257,  258,  259,  260,  261,  261,  261,  262,
      263,  264,  265,  266,  268,  269,  271,  272,  273,  274,
      275,  276,  277,  278,  279,  280,  281,  282,  284,  285,
      286,  287,  288,  289,  291,  292,  293,  294,  295,  296,

      297,  299,  301,  302,  303,  304,  305,  306,  308,  309,
      310,  312,  313,  314,  315,  316,  317,  318,  319,  321,
      322,  323,  324,  326,  327,  328,  329,  330,  331,  333,
      334,  337,  338,  340,  341,  342,  344,  345,  346,  347,
      348,  349,  350,  351,  352,  353,  354,  356,  357,  358,
      359,  360,  361,  362,  364,  365,  366,  367,  368,  369,
      371,  372,  373,  374,  375,  376,  377,  378,  379,  380,
      381,  383,  384,  384,  386,  387,  389,  391,  392,  393,
      395,  396,  398,  399,  401,  403,  405,  407,  408,  410,
      411,  412,  413,  414,  416,  418,  419,  420,  421,  423,

      425,  427,  429,  430,  432,  433,  435,  436,  437,  438,
      440,  442,  444,  445,  446,  447,  449,  450,  451,  452,
      453,  454,  455,  456,  457,  459,  461,  463,  464,  465,
      467,  468,  469,  470,  471,  472,  473,  474,  475,  476,
      477,  478,  480,  481,  482,  483,  484,  486,  487,  488,
      490,  491,  492,  493,  494,  496,  497,  498,  500,  501,
      503,  504,  505,  506,  507,  508,  510,  511,  513,  514,
      515,  516,  517,  517,  518,  520,  521,  523,  525,  527,
      528,  530,  532,  534,  536,  538,  540,  541,  542,  543,
      544,  545,  547,  549,  550,  552,  554,  556,  557,  558,

      560,  561,  563,  565,  566,  567,  568,  570,  572,  574,
      575,  576,  577,  578,  579,  580,  582,  583,  584,  585,
      586,  587,  588,  590,  591,  593,  594,  595,  596,  597,
      598,  599,  600,  601,  602,  604,  606,  607,  608,  610,
      611,  613,  615,  617,  619,  620,  622,  624,  625,  626,
      627,  630,  632,  633,  635,  636,  637,  639,  641,  642,
      644,  645,  646,  647,  648,  649,  650,  651,  653,  654,
      656,  658,  659,  661,  663,  666,  667,  669,  671,  673,
      675,  676,  678,  679,  680,  681,  683,  684,  685,  687,
      689,  691,  692,  694,  695,  696,  697,  698,  699,  701,

      702,  703,  705,  706,  707,  709,  710,  712,  714,  716,
      718,  719,  720,  721,  722,  724,  725,  726,  727,  729,
      731,  733,  735,  737,  738,  740,  742,  744,  746,  746
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[62] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    4,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[537] =
    {   0,
        0,    0,  604,  605,   60,   62,  579,   61,  578,   60,
       65,  605,  605,  577,   57,  605,   57,  589,   59,   59,
      578,  605,   62,  574,   63,  605,  605,  605,  573,    0,
       57,   52,   73,   58,   72,   88,  550,  539,   81,   87,
      548,   64,   62,   93,  104,  107,  121,   98,   57,  117,
      547,  605,   90,  605,  605,  160,  605,   67,  605,  589,
      605,  605,  605,  144,  156,  583,  163,  605,  605,  605,
      605,  579,  605,  578,    0,  605,  156,  163,  170,  605,
      564,  562,  605,  605,  562,  605,    0,  535,  538,  548,
      542,  549,  529,  533,  542,  117,  528,  146,  544,  530,

      133,  147,   92,  522,  523,  520,  534,  523,  160,  529,
      525,  521,  164,  517,  162,  514,  513,  516,  512,  515,
      509,  523,  526,  508,  162,  165,  521,  164,  169,  504,
      504,  522,  498,  166,  518,  169,  505,  497,  516,  501,
      176,  510,  496,  183,  504,  498,  498,  509,  176,  166,
      493,  489,  498,  488,  496,  191,  495,  485,  605,  605,
      605,  530,  605,  605,  211,  605,  521,  219,    0,  223,
      605,  605,  605,    0,  481,  499,  484,  483,  204,  484,
      494,  489,  490,  472,  479,  472,  471,    0,  469,  480,
      470,  178,  460,  476,  463,  481,  476,  478,  474,  465,

      474,  207,  457,  456,  461,  468,  206,  448,  457,  466,
        0,  445,  463,  449,  451,  450,  444,  456,    0,  438,
      448,  207,  227,  453,  445,  437,  451,  451,    0,  437,
        0,  434,    0,  433,  447,    0,  429,  430,  437,  216,
      427,  427,  432,  433,  426,  429,  434,  436,  437,  419,
      418,  204,  417,  428,  419,  421,  414,  417,  213,    0,
      426,  421,  415,  408,  423,  408,  411,  409,  402,  410,
      421,  440,  248,  411,  413,  409,  235,  402,  397,    0,
      403,    0,  405,    0,    0,    0,    0,  393,    0,  399,
      390,  400,  389,    0,    0,  386,  386,  393,    0,    0,

        0,    0,  417,    0,  398,    0,  400,  381,  382,    0,
        0,    0,  383,  384,  392,    0,  376,  377,  392,  377,
      379,  377,  369,  238,    0,    0,    0,  369,  374,    0,
      368,  384,  225,  367,  367,  382,  377,  372,  371,  358,
      360,    0,  373,  374,  355,  369,    0,  358,  363,    0,
      362,  356,  366,  365,    0,  355,  353,    0,  342,    0,
      361,  359,  355,  354,  339,    0,  341,    0,  351,  337,
      351,  350,  252,  260,    0,  337,    0,    0,    0,  349,
        0,    0,    0,    0,    0,    0,  338,  342,  338,  344,
      343,    0,    0,  326,    0,    0,    0,  342,  344,    0,

      339,    0,    0,  342,  322,  327,    0,    0,    0,  336,
      323,  313,  331,  321,  330,    0,  314,  330,  329,  317,
      315,  315,    0,  218,    0,  324,  321,  320,  322,  317,
      303,  314,  320,  319,    0,    0,  314,  304,    0,  316,
        0,    0,    0,    0,  299,    0,    0,  294,  307,  293,
        0,    0,  306,    0,  298,  309,    0,    0,  305,    0,
      307,  298,  286,  282,  303,  298,  282,    0,  297,    0,
        0,  286,    0,    0,    0,  290,    0,    0,    0,    0,
      278,    0,  291,  291,  283,    0,  289,  279,    0,    0,
        0,  279,    0,  288,  276,  284,  287,  274,    0,  281,

      280,    0,  279,  275,    0,  249,    0,    0,    0,    0,
      247,  231,  232,  226,    0,  238,  168,  119,    0,    0,
        0,    0,    0,   45,    0,    0,    0,    0,  605,  285,
      290,  293,  294,  299,  304,  309
    } ;

static yyconst short int yy_def[537] =
    {   0,
      529,    1,  529,  529,  529,  529,  529,  530,  529,  529,
      531,  529,  529,  529,  529,  529,  529,  529,  529,  532,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  529,  529,  529,  529,  529,  529,  530,  529,  530,
      529,  529,  529,  534,  534,  529,  534,  529,  529,  529,
      529,  529,  529,  535,  536,  529,  529,  532,  532,  529,
      529,  529,  529,  529,  529,  529,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,

      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  529,  529,
      529,  534,  529,  529,  534,  529,  535,  535,  536,  529,
      529,  529,  529,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,

      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  535,  529,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,

      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  529,  529,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,

      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,

      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,    0,  529,
      529,  529,  529,  529,  529,  529
    } ;

static yyconst short int yy_nxt[667] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   20,   20,   20,
       21,   22,   23,   24,   25,   26,   27,    4,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       30,   30,   40,   41,   42,   43,   44,   30,   45,   46,
       47,   48,   49,   50,   51,   30,   30,   52,   53,   54,
       55,   56,   56,   56,   56,   59,   62,   65,   69,   74,
       71,   59,   66,   77,   75,   78,   78,   78,   78,  528,
       70,   72,   76,   63,   81,   82,   84,   85,   60,   88,
       89,   93,   67,  103,   60,  128,  154,   94,  131,  129,

       95,   90,  155,  104,   96,   97,   91,   92,   98,  130,
      132,   99,  100,  159,  105,  101,  106,  119,  102,  109,
      107,  122,  110,  120,  123,  121,  108,  111,  196,  124,
      112,  113,  125,  114,  197,  126,  115,  116,  133,  136,
      139,  134,  152,  137,  135,  140,  141,  153,  160,  138,
      156,  161,  146,  142,  143,  157,  147,  144,  148,  149,
      145,   56,   56,  163,  189,  529,  182,  183,  527,  150,
      165,  162,  170,  170,  170,  170,  151,   77,  190,   78,
       78,   78,   78,  162,  529,  185,  529,  529,  529,  529,
      191,  192,  203,  193,  186,  208,  194,  212,  195,  223,

      230,  213,  204,  209,  225,  237,  224,  228,  229,  210,
      226,  238,  240,  246,  251,  257,  526,  259,  163,  241,
      247,  260,  231,  232,  258,  302,  266,  291,  292,  168,
      267,  252,  248,  268,  272,  278,  269,  308,  162,  170,
      170,  170,  170,  352,  324,  325,  322,  339,  360,  279,
      303,  309,  323,  378,  407,  353,  413,  361,  273,  326,
      472,  373,  473,  340,  374,  374,  374,  374,  374,  374,
      374,  374,  525,  379,  524,  414,  374,  374,  374,  374,
      523,  522,  521,  520,  408,   58,   58,   58,   58,   58,
       64,   64,   64,   64,   64,   79,   79,   87,   87,   65,

       65,   65,   65,   65,  167,  167,  167,  167,  167,  169,
      519,  169,  169,  169,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,
      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  485,  484,  483,
      482,  481,  480,  479,  478,  477,  476,  475,  474,  471,
      470,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  431,

      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  412,  411,  410,  409,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  377,  376,  375,
      168,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  359,  358,  357,  356,  355,  354,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  321,  320,  319,  318,  317,  316,  315,  314,  313,

      312,  311,  310,  307,  306,  305,  304,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  277,  276,  275,
      274,  168,  529,  271,  270,  265,  264,  263,  262,  261,
      256,  255,  254,  253,  250,  249,  245,  244,  243,  242,
      239,  236,  235,  234,  233,  227,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  211,  207,  206,  205,  202,
      201,  200,  199,  198,  188,  187,  184,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  168,  166,
      164,  529,  158,  127,  118,  117,   86,   83,   80,   73,

       68,   61,   57,  529,    3,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529
    } ;

static yyconst short int yy_chk[667] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    6,    6,    8,   10,   11,   15,   19,
       17,   58,   11,   20,   19,   20,   20,   20,   20,  524,
       15,   17,   19,   10,   23,   23,   25,   25,    8,   31,
       31,   32,   11,   34,   58,   42,   49,   32,   43,   42,

       32,   31,   49,   34,   33,   33,   31,   31,   33,   42,
       43,   33,   33,   53,   35,   33,   35,   39,   33,   36,
       35,   40,   36,   39,   40,   39,   35,   36,  103,   40,
       36,   36,   40,   36,  103,   40,   36,   36,   44,   45,
       46,   44,   48,   45,   44,   46,   46,   48,   53,   45,
       50,   64,   47,   46,   46,   50,   47,   46,   47,   47,
       46,   56,   56,   65,  101,   67,   96,   96,  518,   47,
       67,   64,   77,   77,   77,   77,   47,   78,  101,   78,
       78,   78,   78,   65,   79,   98,   79,   79,   79,   79,
      102,  102,  109,  102,   98,  113,  102,  115,  102,  125,

      129,  115,  109,  113,  126,  134,  125,  128,  128,  113,
      126,  134,  136,  141,  144,  149,  517,  150,  165,  136,
      141,  150,  129,  129,  149,  202,  156,  192,  192,  168,
      156,  144,  141,  156,  168,  179,  156,  207,  165,  170,
      170,  170,  170,  252,  223,  223,  222,  240,  259,  179,
      202,  207,  222,  277,  324,  252,  333,  259,  170,  223,
      424,  273,  424,  240,  273,  273,  273,  273,  373,  373,
      373,  373,  516,  277,  514,  333,  374,  374,  374,  374,
      513,  512,  511,  506,  324,  530,  530,  530,  530,  530,
      531,  531,  531,  531,  531,  532,  532,  533,  533,  534,

      534,  534,  534,  534,  535,  535,  535,  535,  535,  536,
      504,  536,  536,  536,  503,  501,  500,  498,  497,  496,
      495,  494,  492,  488,  487,  485,  484,  483,  481,  476,
      472,  469,  467,  466,  465,  464,  463,  462,  461,  459,
      456,  455,  453,  450,  449,  448,  445,  440,  438,  437,
      434,  433,  432,  431,  430,  429,  428,  427,  426,  422,
      421,  420,  419,  418,  417,  415,  414,  413,  412,  411,
      410,  406,  405,  404,  401,  399,  398,  394,  391,  390,
      389,  388,  387,  380,  376,  372,  371,  370,  369,  367,
      365,  364,  363,  362,  361,  359,  357,  356,  354,  353,

      352,  351,  349,  348,  346,  345,  344,  343,  341,  340,
      339,  338,  337,  336,  335,  334,  332,  331,  329,  328,
      323,  322,  321,  320,  319,  318,  317,  315,  314,  313,
      309,  308,  307,  305,  303,  298,  297,  296,  293,  292,
      291,  290,  288,  283,  281,  279,  278,  276,  275,  274,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  258,  257,  256,  255,  254,  253,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  239,
      238,  237,  235,  234,  232,  230,  228,  227,  226,  225,
      224,  221,  220,  218,  217,  216,  215,  214,  213,  212,

      210,  209,  208,  206,  205,  204,  203,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  191,  190,  189,  187,
      186,  185,  184,  183,  182,  181,  180,  178,  177,  176,
      175,  167,  162,  158,  157,  155,  154,  153,  152,  151,
      148,  147,  146,  145,  143,  142,  140,  139,  138,  137,
      135,  133,  132,  131,  130,  127,  124,  123,  122,  121,
      120,  119,  118,  117,  116,  114,  112,  111,  110,  108,
      107,  106,  105,  104,  100,   99,   97,   95,   94,   93,
       92,   91,   90,   89,   88,   85,   82,   81,   74,   72,
       66,   60,   51,   41,   38,   37,   29,   24,   21,   18,

       14,    9,    7,    3,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 3 "lexer.l"
    #include "parser.tab.h"
    #include <ctype.h>   
    char* to_upper(char* text) {
        for (int i = 0; text[i] != '\0'; i++) {
            text[i] = toupper(text[i]);
        }
        return text;    
    }
#line 788 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 24 "lexer.l"


    /* Keywords */

#line 944 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 530 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 605 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 28 "lexer.l"
{ printf("\nKeyword: %s\n", yytext); return INT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "lexer.l"
{ printf("\nKeyword: %s\n", yytext); return RETURN; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return AND;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return BOOL;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return BREAK;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return CHAR;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return CONTINUE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return DO;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return ELSE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return FLOAT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return FOR;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return IF;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "lexer.l"
{ printf("\nKeyword: %s\n", yytext); return VOID; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "lexer.l"
{ printf("\nKeyword: %s\n", yytext); return WHILE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return OR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return CONST;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return FALSE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return TRUE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "lexer.l"
{printf("\nKeyword: %s\n", yytext); return STRING_TYPE;}
	YY_BREAK
case 20:
#line 48 "lexer.l"
case 21:
#line 49 "lexer.l"
case 22:
#line 50 "lexer.l"
case 23:
#line 51 "lexer.l"
case 24:
#line 52 "lexer.l"
case 25:
#line 53 "lexer.l"
case 26:
#line 54 "lexer.l"
case 27:
#line 55 "lexer.l"
case 28:
#line 56 "lexer.l"
case 29:
#line 57 "lexer.l"
case 30:
#line 58 "lexer.l"
case 31:
#line 59 "lexer.l"
case 32:
#line 60 "lexer.l"
case 33:
#line 61 "lexer.l"
case 34:
#line 62 "lexer.l"
case 35:
#line 63 "lexer.l"
case 36:
#line 64 "lexer.l"
case 37:
#line 65 "lexer.l"
case 38:
#line 66 "lexer.l"
case 39:
#line 67 "lexer.l"
case 40:
#line 68 "lexer.l"
case 41:
#line 69 "lexer.l"
case 42:
#line 70 "lexer.l"
case 43:
#line 71 "lexer.l"
case 44:
#line 72 "lexer.l"
case 45:
#line 73 "lexer.l"
case 46:
#line 74 "lexer.l"
case 47:
#line 75 "lexer.l"
case 48:
#line 76 "lexer.l"
case 49:
#line 77 "lexer.l"
case 50:
#line 78 "lexer.l"
case 51:
#line 79 "lexer.l"
case 52:
#line 80 "lexer.l"
case 53:
#line 81 "lexer.l"
case 54:
#line 82 "lexer.l"
case 55:
#line 83 "lexer.l"
case 56:
#line 84 "lexer.l"
case 57:
#line 85 "lexer.l"
case 58:
#line 86 "lexer.l"
case 59:
#line 87 "lexer.l"
case 60:
#line 88 "lexer.l"
case 61:
#line 89 "lexer.l"
case 62:
#line 90 "lexer.l"
case 63:
#line 91 "lexer.l"
case 64:
#line 92 "lexer.l"
case 65:
#line 93 "lexer.l"
case 66:
#line 94 "lexer.l"
case 67:
#line 95 "lexer.l"
case 68:
#line 96 "lexer.l"
case 69:
#line 97 "lexer.l"
case 70:
#line 98 "lexer.l"
case 71:
#line 99 "lexer.l"
case 72:
#line 100 "lexer.l"
case 73:
#line 101 "lexer.l"
case 74:
#line 102 "lexer.l"
case 75:
#line 103 "lexer.l"
case 76:
#line 104 "lexer.l"
case 77:
#line 105 "lexer.l"
case 78:
#line 106 "lexer.l"
case 79:
#line 107 "lexer.l"
case 80:
#line 108 "lexer.l"
case 81:
#line 109 "lexer.l"
case 82:
#line 110 "lexer.l"
case 83:
#line 111 "lexer.l"
case 84:
#line 112 "lexer.l"
case 85:
#line 113 "lexer.l"
case 86:
#line 114 "lexer.l"
case 87:
#line 115 "lexer.l"
case 88:
#line 116 "lexer.l"
case 89:
#line 117 "lexer.l"
case 90:
#line 118 "lexer.l"
case 91:
#line 119 "lexer.l"
case 92:
#line 120 "lexer.l"
case 93:
#line 121 "lexer.l"
case 94:
#line 122 "lexer.l"
case 95:
#line 123 "lexer.l"
case 96:
#line 124 "lexer.l"
case 97:
#line 125 "lexer.l"
case 98:
#line 126 "lexer.l"
case 99:
#line 127 "lexer.l"
case 100:
#line 128 "lexer.l"
case 101:
#line 129 "lexer.l"
case 102:
#line 130 "lexer.l"
case 103:
#line 131 "lexer.l"
case 104:
#line 132 "lexer.l"
case 105:
#line 133 "lexer.l"
case 106:
#line 134 "lexer.l"
case 107:
#line 135 "lexer.l"
case 108:
#line 136 "lexer.l"
case 109:
#line 137 "lexer.l"
case 110:
#line 138 "lexer.l"
case 111:
#line 139 "lexer.l"
case 112:
#line 140 "lexer.l"
case 113:
#line 141 "lexer.l"
case 114:
#line 142 "lexer.l"
case 115:
#line 143 "lexer.l"
case 116:
#line 144 "lexer.l"
case 117:
#line 145 "lexer.l"
case 118:
#line 146 "lexer.l"
case 119:
#line 147 "lexer.l"
case 120:
#line 148 "lexer.l"
case 121:
#line 149 "lexer.l"
case 122:
#line 150 "lexer.l"
case 123:
#line 151 "lexer.l"
case 124:
#line 152 "lexer.l"
case 125:
#line 153 "lexer.l"
case 126:
YY_RULE_SETUP
#line 153 "lexer.l"
{yytext = to_upper(yytext);printf("\nKeyword: %s\n", yytext);return *yytext;}   
	YY_BREAK
/************/
/* Operators */
case 127:
#line 158 "lexer.l"
case 128:
#line 159 "lexer.l"
case 129:
#line 160 "lexer.l"
case 130:
#line 161 "lexer.l"
case 131:
#line 162 "lexer.l"
case 132:
YY_RULE_SETUP
#line 162 "lexer.l"
{printf("\nOperator: %s\n", yytext); return LTE;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 163 "lexer.l"
{printf("\nOperator: %s\n", yytext); return GTE;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 164 "lexer.l"
{printf("\nOperator: %s\n", yytext); return EQ;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 165 "lexer.l"
{printf("\nOperator: %s\n", yytext); return NEQ;}
	YY_BREAK
case 136:
#line 167 "lexer.l"
case 137:
#line 168 "lexer.l"
case 138:
YY_RULE_SETUP
#line 168 "lexer.l"
{printf("\nOperator: %s\n", yytext); return AND;}             
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 169 "lexer.l"
{printf("\nOperator: %s\n", yytext); return OR;}              
	YY_BREAK
case 140:
#line 171 "lexer.l"
case 141:
#line 172 "lexer.l"
case 142:
#line 173 "lexer.l"
case 143:
#line 174 "lexer.l"
case 144:
#line 175 "lexer.l"
case 145:
#line 176 "lexer.l"
case 146:
#line 177 "lexer.l"
case 147:
#line 178 "lexer.l"
case 148:
#line 179 "lexer.l"
case 149:
#line 180 "lexer.l"
case 150:
#line 181 "lexer.l"
case 151:
#line 182 "lexer.l"
case 152:
#line 183 "lexer.l"
case 153:
#line 184 "lexer.l"
case 154:
#line 185 "lexer.l"
case 155:
#line 186 "lexer.l"
case 156:
#line 187 "lexer.l"
case 157:
#line 188 "lexer.l"
case 158:
#line 189 "lexer.l"
case 159:
YY_RULE_SETUP
#line 189 "lexer.l"
{printf("\nOperator: %s\n", yytext); return '<';}              
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 190 "lexer.l"
{printf("\nOperator: %s\n", yytext); return '>';}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 191 "lexer.l"
{printf("\nOperator: %s\n", yytext); return NOT;}                    
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 192 "lexer.l"
{printf("\nOperator: %s\n", yytext); return NOT;}                    
	YY_BREAK
case 163:
#line 194 "lexer.l"
case 164:
#line 195 "lexer.l"
case 165:
#line 196 "lexer.l"
case 166:
#line 197 "lexer.l"
case 167:
#line 198 "lexer.l"
case 168:
#line 199 "lexer.l"
case 169:
#line 200 "lexer.l"
case 170:
#line 201 "lexer.l"
case 171:
#line 202 "lexer.l"
case 172:
#line 203 "lexer.l"
case 173:
#line 204 "lexer.l"
case 174:
#line 205 "lexer.l"
case 175:
#line 206 "lexer.l"
case 176:
#line 207 "lexer.l"
case 177:
#line 208 "lexer.l"
case 178:
YY_RULE_SETUP
#line 208 "lexer.l"
{printf("\nOperator: %s\n", yytext); return *yytext;}
	YY_BREAK
/************/
case 179:
YY_RULE_SETUP
#line 211 "lexer.l"
{printf("\nCommend: { %s }\n", yytext);/*ignore further*/}
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 212 "lexer.l"
{fprintf(stderr, "\nError at line %d: Invalid number '%s'\n", yylineno, yytext);}
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 213 "lexer.l"
{printf("\nInteger: %s\n", yytext); return INTEGER;}
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 214 "lexer.l"
{printf("\nFloat: %s\n", yytext); return FLOAT;}
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 215 "lexer.l"
{printf("\nChar : %s\n", yytext);return CHARACTER;}
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 216 "lexer.l"
{ printf("\nString: %s\n", yytext); return STRING; }
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 217 "lexer.l"
{ printf("\nString: %s\n", yytext); return STRING; }
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 218 "lexer.l"
{printf("\nIdentifier: %s\n", yytext); return IDENTIFIER;}
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 219 "lexer.l"
{/* Ignore whitespace*/}
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 220 "lexer.l"
{printf("\nUnknown character: %s\n", yytext); return *yytext;}
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 222 "lexer.l"
ECHO;
	YY_BREAK
#line 1542 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 530 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 530 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 529);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 222 "lexer.l"

int yywrap() {
    return 1;
}
